---
title: "Extended Figure 1"
author: "Lin Tian"
date: "2/4/2017"
output: html_document
---

In **Extended Figure 1**, we compared GPAG signatures and PPAG signatures generated by principal componenet analysis and sum of genes.

Again, you need apply to the access to [METABRIC Dataset](https://ega-archive.org/dacs/EGAC00001000484).

```{r}
load("~/rstudio/lintian/metabric.exp.RData") # load METABRIC Discovery Dataset; you need apply to the access to the dataset
load("~/vesselNormalization/data/GPAGs_PPAGs.RData") ## load GPAGs and PPAGs
library(survival)
library(ggplot2)
```

### Calculate Signatures

```{r}
## GPAGs
GPAGs_matrix <- as.matrix(metabric.d.exp[, GPAGs])
GPAGs_svd <- svd(sweep(GPAGs_matrix, 2, colMeans(GPAGs_matrix), "-"))
GPAGs_PC1 <- -GPAGs_svd$u[, 1] ## PCA approach
cor.test(GPAGs_PC1, apply(GPAGs_matrix, 1, sum))
head(GPAGs_svd$d^2/sum(GPAGs_svd$d^2))

### PCA
GPAGs_PC1.group <- cut(GPAGs_PC1, breaks = quantile(GPAGs_PC1, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "medium", "high"))
GPAGs_PC1.group[is.na(GPAGs_PC1.group)] = "low"
GPAGs_PC1.group <- factor(GPAGs_PC1.group, levels=c("high", "medium", "low"))

### Sum of the Genes
GPAGs_sum <- apply(GPAGs_matrix, 1, sum)
GPAGs_sum.group <- cut(GPAGs_sum, breaks = quantile(GPAGs_sum, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "medium", "high"))
GPAGs_sum.group[is.na(GPAGs_sum.group)] = "low"
GPAGs_sum.group <- factor(GPAGs_sum.group, levels=c("high", "medium", "low"))


## PPAGs
PPAGs_matrix <- as.matrix(metabric.d.exp[, PPAGs])
PPAGs_svd <- svd(sweep(PPAGs_matrix, 2, colMeans(PPAGs_matrix), "-"))
PPAGs_PC1 <- -PPAGs_svd$u[, 1] ## PCA approach
cor.test(PPAGs_PC1, apply(PPAGs_matrix, 1, sum))
head(PPAGs_svd$d^2/sum(PPAGs_svd$d^2))

### PCA
PPAGs_PC1.group <- cut(PPAGs_PC1, breaks = quantile(PPAGs_PC1, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "medium", "high"))
PPAGs_PC1.group[is.na(PPAGs_PC1.group)] = "low"
PPAGs_PC1.group <- factor(PPAGs_PC1.group, levels=c("high", "medium", "low"))

### Sum of the Genes
PPAGs_sum <- apply(PPAGs_matrix, 1, sum)
PPAGs_sum.group <- cut(PPAGs_sum, breaks = quantile(PPAGs_sum, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "medium", "high"))
PPAGs_sum.group[is.na(PPAGs_sum.group)] = "low"
PPAGs_sum.group <- factor(PPAGs_sum.group, levels=c("high", "medium", "low"))


## Combined Score: GPAGs - PPAGs
PCA_Sum_metabric.d <- data.frame(GPAGs_PC1=GPAGs_PC1, GPAGs_sum=GPAGs_sum, PPAGs_PC1=PPAGs_PC1, PPAGs_sum=PPAGs_sum, 
                                 combined_PC1=GPAGs_PC1-PPAGs_PC1, combined_sum=GPAGs_sum-PPAGs_sum)

### PCA
combined_PC1.group <- cut(PCA_Sum_metabric.d$combined_PC1, breaks = quantile(PCA_Sum_metabric.d$combined_PC1, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "medium", "high"))
combined_PC1.group[is.na(combined_PC1.group)] = "low"
combined_PC1.group <- factor(combined_PC1.group, levels=c("high", "medium", "low"))

### Sum of the Genes
combined_sum.group <- cut(PCA_Sum_metabric.d$combined_sum, breaks = quantile(PCA_Sum_metabric.d$combined_sum, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "medium", "high"))
combined_sum.group[is.na(combined_sum.group)] = "low"
combined_sum.group <- factor(combined_sum.group, levels=c("high", "medium", "low"))
```

### Extended Fig1 a

```{r}
## GPAGs
ggplot(PCA_Sum_metabric.d, aes(GPAGs_PC1, GPAGs_sum))+geom_point(alpha=0.8)+geom_smooth(method=lm)+xlab("The 1st PC of GPAGs (35.6%)")+ylab("Sum of GPAGs")+theme_bw()+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())+scale_size_area()
cor.test(PCA_Sum_metabric.d$GPAGs_PC1, PCA_Sum_metabric.d$GPAGs_sum)

## PPAGs
ggplot(PCA_Sum_metabric.d, aes(PPAGs_PC1, PPAGs_sum))+geom_point(alpha=0.8)+geom_smooth(method=lm)+xlab("The 1st PC of PPAGs (29.7%)")+ylab("Sum of PPAGs")+theme_bw()+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())+scale_size_area()
cor.test(PCA_Sum_metabric.d$PPAGs_PC1, PCA_Sum_metabric.d$PPAGs_sum)

## Combined Score
ggplot(PCA_Sum_metabric.d, aes(combined_PC1, combined_sum))+geom_point(alpha=0.8)+geom_smooth(method=lm)+xlab("Combined Score (PCA)")+ylab("(Sum of GPAGs)-(Sum of PPAGs)")+theme_bw()+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())+scale_size_area()
cor.test(PCA_Sum_metabric.d$combined_PC1, PCA_Sum_metabric.d$combined_sum)
```


### Extended Fig1 b

```{r}
## GPAGs
survdiff(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ GPAGs_sum.group)
coxph(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ GPAGs_sum.group)
plot(survfit(Surv(metabric.d.ann$T/30, metabric.d.ann$DSS) ~ GPAGs_sum.group), col=c("red", "orange", "green"), lty=1, xlab = "Months", ylab = "Disease-Free Survival Freq", ylim=c(0, 1), mark.time = TRUE)
legend("bottomleft", c("high (47/324)", "med (88/326)", "low (125/330)"), col=c("red", "orange", "green"), lty=1, bty = "n", lwd=4)


## PPAGs
survdiff(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ PPAGs_sum.group)
coxph(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ PPAGs_sum.group)
plot(survfit(Surv(metabric.d.ann$T/30, metabric.d.ann$DSS) ~ PPAGs_sum.group), col=c("red", "orange", "green"), lty=1, xlab = "Months", ylab = "Disease-Free Survival Freq", ylim=c(0, 1), mark.time = TRUE)
legend("bottomleft", c("high (143/328)", "med (68/325)", "low (49/327)"), col=c("red", "orange", "green"), lty=1, bty = "n", lwd=4)

## Combined Score
survdiff(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ combined_sum.group)
coxph(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ combined_sum.group)
plot(survfit(Surv(metabric.d.ann$T/30, metabric.d.ann$DSS) ~ combined_PC1.group), col=c("red", "orange", "green"), lty=1, xlab = "Months", ylab = "Disease-Free Survival Freq", ylim=c(0, 1), mark.time = TRUE)
legend("bottomleft", c("high (44/323)", "med (77/327)", "low (139/330)"), col=c("red", "orange", "green"), lty=1, bty = "n", lwd=4)
```

### Extended Fig1 c

```{r}
## GPAGs
survdiff(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ GPAGs_PC1.group)
coxph(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ GPAGs_PC1.group)
plot(survfit(Surv(metabric.d.ann$T/30, metabric.d.ann$DSS) ~ GPAGs_PC1.group), col=c("red", "orange", "green"), lty=1, xlab = "Months", ylab = "Disease-Free Survival Freq", ylim=c(0, 1), mark.time = TRUE)
legend("bottomleft", c("high (53/322)", "med (82/327)", "low (125/331)"), col=c("red", "orange", "green"), lty=1, bty = "n", lwd=4)

## PPAGs
survdiff(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ PPAGs_PC1.group)
coxph(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ PPAGs_PC1.group)
plot(survfit(Surv(metabric.d.ann$T/30, metabric.d.ann$DSS) ~ PPAGs_PC1.group), col=c("red", "orange", "green"), lty=1, xlab = "Months", ylab = "Disease-Free Survival Freq", ylim=c(0, 1), mark.time = TRUE)
legend("bottomleft", c("high (126/326)", "med (78/327)", "low (56/327)"), col=c("red", "orange", "green"), lty=1, bty = "n", lwd=4)

## Combined Score
survdiff(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ combined_PC1.group)
coxph(Surv(metabric.d.ann$T, metabric.d.ann$DSS) ~ combined_PC1.group)
plot(survfit(Surv(metabric.d.ann$T/30, metabric.d.ann$DSS) ~ combined_PC1.group), col=c("red", "orange", "green"), lty=1, xlab = "Months", ylab = "Disease-Free Survival Freq", ylim=c(0, 1), mark.time = TRUE)
legend("bottomleft", c("high (49/323)", "med (73/329)", "low (138/328)"), col=c("red", "orange", "green"), lty=1, bty = "n", lwd=4)
```
