---
title: "Image Simulation for Activated CD4+ T Cells"
author: "Lin Tian"
date: "8/26/2016"
output: html_document
---

## Read Data

We use `gdata` package to read Excel file.

```{r}
library(gdata)
setwd("~/vesselNormalization/ExtendedFig9")
DAPI_ch <- read.xls("~/vesselNormalization/data/ImageSimulation.xlsx", sheet=1, as.is=TRUE)
CFSE_ch <- read.xls("~/vesselNormalization/data/ImageSimulation.xlsx", sheet=2, as.is=TRUE)
tdRed_ch <- read.xls("~/vesselNormalization/data/ImageSimulation.xlsx", sheet=3, as.is=TRUE)
lectin_ch <- read.xls("~/vesselNormalization/data/ImageSimulation.xlsx", sheet=4, as.is=TRUE)
```

## Remove Unstimulated CD4+ T Cells in tdRed Channel

```{r}
minLen <- c()
for(s in paste0("S", 1:5)) {
  tdRed_cells <- subset(tdRed_ch, Label==s)
  lectin_cells <- subset(lectin_ch, Label==s)
  dist_mat <- matrix(NA, nrow=nrow(tdRed_cells), ncol=nrow(lectin_cells))
  for(i in 1:nrow(tdRed_cells)) {
      dist_mat[i, ] <- sqrt(sapply(lectin_cells$XStart, function(x) (x-tdRed_cells[i, "XStart"])^2) + sapply(lectin_cells$YStart, function(x) (x-tdRed_cells[i, "YStart"])^2))
  }
  minLen <- c(minLen, apply(dist_mat, 1, min))
}
tdRed_ch$minLen <- minLen

tdRed_ch2 <- data.frame(Label=c(), XStart=c(), YStart=c(), minLen=c())
for(s in paste0("S", 1:5)) {
  print(s)
  CFSE_cells <- subset(CFSE_ch, Label==s)
  tdRed_cells <- subset(tdRed_ch, Label==s)
  if(nrow(CFSE_cells)==0) {
    tdRed_ch2 <- rbind(tdRed_ch2, tdRed_cells)
    next
  }
  else {
    removeTdRedCells <- rep(NA, nrow(CFSE_cells))
    for(cell in 1:nrow(CFSE_cells)) {
    removeTdRedCells[cell] <- which.min(abs(CFSE_cells[cell, "minDistLectin"] - tdRed_cells$minLen))
    print(min(abs(CFSE_cells[cell, "minDistLectin"] - tdRed_cells$minLen)))
    }
  tdRed_cells <- tdRed_cells[-removeTdRedCells, ]
  tdRed_ch2 <- rbind(tdRed_ch2, tdRed_cells)
  }
}
```


## Plot Violin Plot (Extended Data Fig. 9c)

```{r}
library(ggplot2)
### 3 pixels/um
minDistDF <- data.frame(type=c(rep("Naive", nrow(CFSE_ch)), rep("Stimulated", nrow(tdRed_ch2))), Label=c(CFSE_ch$Label, tdRed_ch2$Label), minDist=c(CFSE_ch$minDistLectin, tdRed_ch2$minLen)/3) ### Unit of minDist: um

source("https://raw.githubusercontent.com/lintian0616/tools/master/summarySE.R")
minDistDF_s <- subset(summarySE(minDistDF, measurevar="minDist", groupvars=c("type", "Label")), type=="Stimulated")

t.test(minDistDF_s$minDist, mu=mean(subset(minDistDF, type=="Naive")[, "minDist"]))

ggplot() + geom_hline(yintercept=mean(CFSE_ch$minDistLectin)/3, colour="#252525") + geom_violin(data=minDistDF, aes(x=type, y=minDist), fill=NA) + geom_point(data=minDistDF, aes(x=type, y=minDist, colour=Label), alpha=0.68, shape=16, size=2, position=position_jitterdodge(dodge.width=0.5)) + scale_colour_manual(values=c("#fb9a99","#fdbf6f", "#b2df8a", "#a6cee3", "#cab2d6")) + geom_point(data=minDistDF_s, aes(x=type, y=minDist, fill=Label), shape=21, size=8, position=position_jitterdodge(dodge.width=0.5)) + scale_fill_manual(values=c("#e31a1c", "#ff7f00", "#33a02c", "#1f78b4", "#6a3d9a")) + scale_y_continuous(breaks=seq(0, 1500, by=300), limits=c(0, 1500))+theme_bw()+theme(axis.title.x = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), axis.line.x=element_line(colour="black"), axis.line.y=element_line(colour="black"))+coord_fixed(ratio=0.002)
```

## Random Simulation

We perform 10,000 times of simulation for each sample. In each round of simulation, the number of simulated random dots is same with the real number of CD4+ T cells.

```{r}
simulatedDist <- matrix(NA, nrow=length(paste0("S", 1:5)), ncol=10000)
rownames(simulatedDist) <- paste0("S", 1:5)
set.seed(10000)
for(s in paste0("S", 1:5)) {
  DAPI_cells <- subset(DAPI_ch, Label==s)
  tdRed_cells <- subset(tdRed_ch, Label==s)
  lectin_cells <- subset(lectin_ch, Label==s)
  for(i in 1:ncol(simulatedDist)) {
    tdRed_cells_dist <- rep(NA, nrow(tdRed_cells))
    for(j in 1:nrow(tdRed_cells)) {
      XY_pos <- sample(1:nrow(DAPI_cells), 2, replace=F)
      minX_pos <- min(DAPI_cells[XY_pos, "XStart"])
      maxX_pos <- max(DAPI_cells[XY_pos, "XStart"])
      minY_pos <- min(DAPI_cells[XY_pos, "YStart"])
      maxY_pos <- max(DAPI_cells[XY_pos, "YStart"])
      randomRatio <- runif(1, 0, 1)
      X_pos <- minX_pos + randomRatio*(maxX_pos - minX_pos)
      Y_pos <- minY_pos + randomRatio*(maxY_pos - minY_pos)
      tdRed_cells_dist[j] <- min(sqrt(sapply(lectin_cells$XStart, function(x) (x-X_pos)^2) + sapply(lectin_cells$YStart, function(x) (x-Y_pos)^2)))
    }
    simulatedDist[s, i] <- mean(tdRed_cells_dist)
  }
}
```

## Plot Histogram (Extended Data Fig. 9d)

```{r}
library(ggplot2)

## S1
S1_df <- data.frame(type=c(rep("Real", nrow(subset(tdRed_ch2, Label=="S1"))), rep("Stimulated", ncol(simulatedDist))), minDist=c(as.numeric(subset(tdRed_ch2, Label=="S1")[, "minLen"]), as.numeric(simulatedDist[1, ]))/3) ### Unit of minDist: um

ggplot(data=S1_df) + geom_histogram(data=subset(S1_df, type=="Real"), aes(x=minDist, y = ..density..), fill="#fb9a99", colour=NA, alpha=0.68)  + geom_density(data=subset(S1_df, type=="Real"), aes(x=minDist), colour="#e31a1c") + geom_density(data=subset(S1_df, type=="Stimulated"), aes(x=minDist), colour="#e31a1c", linetype=2) + geom_vline(xintercept = mean(subset(S1_df, type=="Real")[, "minDist"]), colour="#e31a1c") + scale_y_continuous(breaks=seq(0, 0.05, by=0.01), limits=c(0, 0.05), trans = "sqrt")+theme_bw()+theme(axis.title.x = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), axis.line.x=element_line(colour="black"), axis.line.y=element_line(colour="black"))+coord_fixed(ratio=1000)

sum(mean(subset(S1_df, type=="Real")[, "minDist"]) > subset(S1_df, type=="Stimulated")[, "minDist"])


## S2
S2_df <- data.frame(type=c(rep("Real", nrow(subset(tdRed_ch2, Label=="S2"))), rep("Stimulated", ncol(simulatedDist))), minDist=c(as.numeric(subset(tdRed_ch2, Label=="S2")[, "minLen"]), as.numeric(simulatedDist[2, ]))/3) ### Unit of minDist: um

ggplot(data=S2_df) + geom_histogram(data=subset(S2_df, type=="Real"), aes(x=minDist, y = ..density..), fill="#fdbf6f", colour=NA, alpha=0.68)  + geom_density(data=subset(S2_df, type=="Real"), aes(x=minDist), colour="#ff7f00") + geom_density(data=subset(S2_df, type=="Stimulated"), aes(x=minDist), colour="#ff7f00", linetype=2) + geom_vline(xintercept = mean(subset(S2_df, type=="Real")[, "minDist"]), colour="#ff7f00") + scale_y_continuous(breaks=seq(0, 0.06, by=0.02), limits=c(0, 0.06), trans = "sqrt")+theme_bw()+theme(axis.title.x = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), axis.line.x=element_line(colour="black"), axis.line.y=element_line(colour="black"))+coord_fixed(ratio=1200)

sum(mean(subset(S2_df, type=="Real")[, "minDist"]) > subset(S2_df, type=="Stimulated")[, "minDist"])


## S3
S3_df <- data.frame(type=c(rep("Real", nrow(subset(tdRed_ch2, Label=="S3"))), rep("Stimulated", ncol(simulatedDist))), minDist=c(as.numeric(subset(tdRed_ch2, Label=="S3")[, "minLen"]), as.numeric(simulatedDist[3, ]))/3) ### Unit of minDist: um

ggplot(data=S3_df) + geom_histogram(data=subset(S3_df, type=="Real"), aes(x=minDist, y = ..density..), fill="#b2df8a", colour=NA, alpha=0.68)  + geom_density(data=subset(S3_df, type=="Real"), aes(x=minDist), colour="#33a02c") + geom_density(data=subset(S3_df, type=="Stimulated"), aes(x=minDist), colour="#33a02c", linetype=2) + geom_vline(xintercept = mean(subset(S3_df, type=="Real")[, "minDist"]), colour="#33a02c") + scale_y_continuous(breaks=seq(0, 0.10, by=0.02), limits=c(0, 0.10), trans = "sqrt")+theme_bw()+theme(axis.title.x = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), axis.line.x=element_line(colour="black"), axis.line.y=element_line(colour="black"))+coord_fixed(ratio=750)

sum(mean(subset(S3_df, type=="Real")[, "minDist"]) > subset(S3_df, type=="Stimulated")[, "minDist"])


## S4
S4_df <- data.frame(type=c(rep("Real", nrow(subset(tdRed_ch2, Label=="S4"))), rep("Stimulated", ncol(simulatedDist))), minDist=c(as.numeric(subset(tdRed_ch2, Label=="S4")[, "minLen"]), as.numeric(simulatedDist[4, ]))/3) ### Unit of minDist: um

ggplot(data=S4_df) + geom_histogram(data=subset(S4_df, type=="Real"), aes(x=minDist, y = ..density..), fill="#a6cee3", colour=NA, alpha=0.68)  + geom_density(data=subset(S4_df, type=="Real"), aes(x=minDist), colour="#1f78b4") + geom_density(data=subset(S4_df, type=="Stimulated"), aes(x=minDist), colour="#1f78b4", linetype=2) + geom_vline(xintercept = mean(subset(S4_df, type=="Real")[, "minDist"]), colour="#1f78b4") + scale_y_continuous(breaks=seq(0, 0.03, by=0.01), limits=c(0, 0.03), trans = "sqrt")+theme_bw()+theme(axis.title.x = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), axis.line.x=element_line(colour="black"), axis.line.y=element_line(colour="black"))+coord_fixed(ratio=3000)

sum(mean(subset(S4_df, type=="Real")[, "minDist"]) > subset(S4_df, type=="Stimulated")[, "minDist"])


## S5
S5_df <- data.frame(type=c(rep("Real", nrow(subset(tdRed_ch2, Label=="S5"))), rep("Stimulated", ncol(simulatedDist))), minDist=c(as.numeric(subset(tdRed_ch2, Label=="S5")[, "minLen"]), as.numeric(simulatedDist[5, ]))/3) ### Unit of minDist: um

ggplot(data=S5_df) + geom_histogram(data=subset(S5_df, type=="Real"), aes(x=minDist, y = ..density..), fill="#cab2d6", colour=NA, alpha=0.68)  + geom_density(data=subset(S5_df, type=="Real"), aes(x=minDist), colour="#6a3d9a") + geom_density(data=subset(S5_df, type=="Stimulated"), aes(x=minDist), colour="#6a3d9a", linetype=2) + geom_vline(xintercept = mean(subset(S5_df, type=="Real")[, "minDist"]), colour="#6a3d9a") + scale_y_continuous(breaks=seq(0, 0.03, by=0.01), limits=c(0, 0.03), trans = "sqrt")+theme_bw()+theme(axis.title.x = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), axis.line.x=element_line(colour="black"), axis.line.y=element_line(colour="black"))+coord_fixed(ratio=2000)

sum(mean(subset(S5_df, type=="Real")[, "minDist"]) > subset(S5_df, type=="Stimulated")[, "minDist"])
```

